// Pulls download counts from the GitHub Releases API and writes a
// daily snapshot to docs/metrics/snapshots/YYYY-MM-DD.json plus the
// rolling docs/metrics/latest.json. The aggregation is also reflected
// in docs/metrics/README.md so it is browsable from the repo.
//
// Run locally:
//   GITHUB_TOKEN=$(gh auth token) node scripts/metrics/collect.mjs
// Run unauthenticated (lower rate limit, fine for ad-hoc use):
//   node scripts/metrics/collect.mjs
//
// Env:
//   GITHUB_TOKEN        — optional, raises rate limit from 60/h to 5000/h
//   INCLUDE_PRERELEASES — set to "1" to count drafts/pre-releases
//   REPO                — defaults to "nucket/NekoAI"

import { writeFile, mkdir, readFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parseAssetName } from './parse-asset.mjs'

const __dirname = dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = join(__dirname, '..', '..')
const SNAPSHOTS_DIR = join(REPO_ROOT, 'docs', 'metrics', 'snapshots')
const LATEST_PATH = join(REPO_ROOT, 'docs', 'metrics', 'latest.json')
const README_PATH = join(REPO_ROOT, 'docs', 'metrics', 'README.md')
const SCHEMA_VERSION = 1

const REPO = process.env.REPO || 'nucket/NekoAI'
const INCLUDE_PRERELEASES = process.env.INCLUDE_PRERELEASES === '1'

async function fetchReleases() {
  const headers = {
    'User-Agent': 'nekoai-metrics-collector',
    Accept: 'application/vnd.github+json',
  }
  if (process.env.GITHUB_TOKEN) headers.Authorization = `Bearer ${process.env.GITHUB_TOKEN}`
  const url = `https://api.github.com/repos/${REPO}/releases?per_page=100`
  const res = await fetch(url, { headers })
  if (!res.ok) {
    const body = await res.text().catch(() => '')
    throw new Error(`GitHub API ${res.status} ${res.statusText}: ${body.slice(0, 200)}`)
  }
  return res.json()
}

function buildSnapshot(releases) {
  const filtered = releases.filter((r) => INCLUDE_PRERELEASES || (!r.draft && !r.prerelease))

  const totals = { all: 0, by_os: {}, by_arch: {}, by_version: {}, by_format: {} }
  const unknown = []
  const out = []

  for (const r of filtered) {
    const releaseEntry = { tag: r.tag_name, published_at: r.published_at, assets: [] }
    let releaseTotal = 0

    for (const a of r.assets || []) {
      const parsed = parseAssetName(a.name)
      if (parsed === null) {
        unknown.push({ tag: r.tag_name, name: a.name, download_count: a.download_count })
        continue
      }
      if (parsed.skip) continue

      const dc = a.download_count || 0
      releaseEntry.assets.push({
        name: a.name,
        os: parsed.os,
        arch: parsed.arch,
        format: parsed.format,
        download_count: dc,
        size: a.size,
      })
      releaseTotal += dc
      totals.all += dc
      totals.by_os[parsed.os] = (totals.by_os[parsed.os] || 0) + dc
      totals.by_arch[parsed.arch] = (totals.by_arch[parsed.arch] || 0) + dc
      totals.by_format[parsed.format] = (totals.by_format[parsed.format] || 0) + dc
    }

    if (releaseTotal > 0 || releaseEntry.assets.length > 0) {
      totals.by_version[r.tag_name] = releaseTotal
    }
    out.push(releaseEntry)
  }

  return {
    schema_version: SCHEMA_VERSION,
    captured_at: new Date().toISOString(),
    source: 'github-releases',
    repo: REPO,
    totals,
    releases: out,
    unknown_assets: unknown,
  }
}

function todayUtc() {
  return new Date().toISOString().slice(0, 10)
}

function renderReadme(snapshot) {
  const t = snapshot.totals
  const lines = []
  lines.push('# NekoAI install metrics')
  lines.push('')
  lines.push('> Auto-generated by `scripts/metrics/collect.mjs`. Do not edit by hand.')
  lines.push(
    '> Source: GitHub Releases download counts (public API). No telemetry runs in the app.'
  )
  lines.push('')
  lines.push(`Captured at: \`${snapshot.captured_at}\``)
  lines.push('')
  lines.push(`**Total downloads: ${t.all}**`)
  lines.push('')
  lines.push('## By operating system')
  lines.push('')
  lines.push('| OS | Downloads |')
  lines.push('| --- | ---: |')
  for (const os of ['windows', 'macos', 'linux']) {
    lines.push(`| ${os} | ${t.by_os[os] || 0} |`)
  }
  lines.push('')
  lines.push('## By architecture')
  lines.push('')
  lines.push('| Arch | Downloads |')
  lines.push('| --- | ---: |')
  for (const arch of Object.keys(t.by_arch).sort()) {
    lines.push(`| ${arch} | ${t.by_arch[arch]} |`)
  }
  lines.push('')
  lines.push('## By installer format')
  lines.push('')
  lines.push('| Format | Downloads |')
  lines.push('| --- | ---: |')
  for (const fmt of Object.keys(t.by_format).sort()) {
    lines.push(`| ${fmt} | ${t.by_format[fmt]} |`)
  }
  lines.push('')
  lines.push('## By release')
  lines.push('')
  lines.push('| Tag | Downloads |')
  lines.push('| --- | ---: |')
  for (const tag of Object.keys(t.by_version).sort().reverse()) {
    lines.push(`| \`${tag}\` | ${t.by_version[tag]} |`)
  }
  lines.push('')
  if (snapshot.unknown_assets.length > 0) {
    lines.push('## Unknown assets')
    lines.push('')
    lines.push(
      'Filenames that did not match any pattern in `parse-asset.mjs`. Add a regex if any of these is a real installer.'
    )
    lines.push('')
    for (const u of snapshot.unknown_assets) {
      lines.push(`- \`${u.name}\` (${u.tag}, ${u.download_count} downloads)`)
    }
    lines.push('')
  }
  lines.push('## How this works')
  lines.push('')
  lines.push(
    'A nightly GitHub Action calls the public GitHub Releases API, sums the `download_count` reported per asset, and writes a snapshot to `snapshots/YYYY-MM-DD.json`. `latest.json` always points at the newest snapshot. Schema documented in `SCHEMA.md`.'
  )
  lines.push('')
  lines.push('Limitations:')
  lines.push('')
  lines.push(
    '- Counts are downloads, not installations — an asset can be downloaded and never installed.'
  )
  lines.push(
    '- Diffing snapshots can yield negative deltas if a release is renamed or an asset is removed; treat the cumulative number as authoritative, not daily deltas.'
  )
  lines.push(
    '- Future install sources (winget, Homebrew, Flathub, Snap) will land as additional `source` files using the same schema.'
  )
  lines.push('')
  return lines.join('\n')
}

async function fileEquals(path, contents) {
  if (!existsSync(path)) return false
  try {
    const current = await readFile(path, 'utf8')
    return current === contents
  } catch {
    return false
  }
}

async function main() {
  const releases = await fetchReleases()
  const snapshot = buildSnapshot(releases)

  await mkdir(SNAPSHOTS_DIR, { recursive: true })
  const snapshotPath = join(SNAPSHOTS_DIR, `${todayUtc()}.json`)
  const snapshotJson = JSON.stringify(snapshot, null, 2) + '\n'
  const latestJson = JSON.stringify(snapshot, null, 2) + '\n'
  const readmeBody = renderReadme(snapshot)

  const snapshotChanged = !(await fileEquals(snapshotPath, snapshotJson))
  const latestChanged = !(await fileEquals(LATEST_PATH, latestJson))
  const readmeChanged = !(await fileEquals(README_PATH, readmeBody))

  if (snapshotChanged) await writeFile(snapshotPath, snapshotJson)
  if (latestChanged) await writeFile(LATEST_PATH, latestJson)
  if (readmeChanged) await writeFile(README_PATH, readmeBody)

  const changed =
    [snapshotChanged && 'snapshot', latestChanged && 'latest', readmeChanged && 'readme']
      .filter(Boolean)
      .join(', ') || 'none'
  console.log(
    `[metrics] total=${snapshot.totals.all} releases=${snapshot.releases.length} unknown=${snapshot.unknown_assets.length} changed=${changed}`
  )
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
